# Generated by Django 5.0.6 on 2024-07-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bigArt", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="artist",
            field=models.CharField(default="Amuku Godwin", max_length=200),
        ),
    ]
