# Generated by Django 5.0.6 on 2024-06-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bigArt", "0003_rename_customer_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(default="username", max_length=100, unique=True),
        ),
    ]
