# Generated by Django 5.0.6 on 2024-07-13 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bigArt", "0004_review"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ceramics",
        ),
        migrations.DeleteModel(
            name="Drawing",
        ),
        migrations.DeleteModel(
            name="Painting",
        ),
        migrations.DeleteModel(
            name="Sculpture",
        ),
    ]
