# Generated by Django 5.0.6 on 2024-06-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bigArt", "0004_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="USERNAME_FIELD",
            field=models.CharField(default="username", max_length=100, unique=True),
        ),
    ]
