# Generated by Django 5.0.6 on 2024-06-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bigArt", "0005_customuser_username_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="USERNAME_FIELD",
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=100),
        ),
    ]
